name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rsync
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avzr --delete --exclude=".git/"
          remote_path: ~/roo.pe/
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/roo.pe/
            docker stop roo.pe
            docker rm roo.pe
            docker run \
              --name roo.pe \
              --env VIRTUAL_HOST=roo.pe \
              --env LETSENCRYPT_HOST=roo.pe \
              --env LETSENCRYPT_EMAIL=roope.merikukka@gmail.com \
              --restart=unless-stopped \
              -v /home/roope/roo.pe:/usr/share/nginx/html:ro \
              --network=nginx-proxy-network \
              -d nginx